### model
model_name_or_path: ../download_model/models--shenzhi-wang--Llama3-8B-Chinese-Chat

### method
stage: sft
do_train: true
do_eval: true
finetuning_type: lora
lora_target: all

### lora

lora_dropout: 0.05
#lora_rank: 8,
# lora_alpha=16,
### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_offload_config.json
# resume_from_checkpoint =output_model_dir,
# use_unsloth=True,   
# train_on_prompt=True,
# upcast_layernorm=True, #正向传播转化为32位，与quantization_bit一同使用
# quantization_bit=8,
#quantization_bit=4,                     # 使用 4 比特 QLoRA
#loraplus_lr_ratio=16.0,                   # 使用 LoRA+ 算法并设置 lambda=16.0

### dataset
dataset: drug_label
template: llama3
cutoff_len: 1400
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../train_models/extract_llama3
logging_steps: 20
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 0.000005
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_steps: 0.1
weight_decay: 0.01
fp16: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 60

### key
hf_hub_token: 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
ms_hub_token: e601d228-b612-477b-ac1b-2aa94dd47267