config_dict = {
    "llama2-7b": {
        "run_exp_config": {
            "stage": "sft",
            "do_train": True,
            "do_eval": True,
            "model_name_or_path": "meta-llama/Llama-2-7b-chat-hf",
            "dataset": "medical_report_category",
            "template": "llama2",
            "finetuning_type": "lora",
            "lora_rank": 8,
            "lora_alpha": 16,
            "lora_dropout": 0.1,
            "lora_target": "all",
            "output_dir": "/content/drive/MyDrive/models/llama2_7b_8batch",
            "per_device_train_batch_size": 8,
            "per_device_eval_batch_size": 1,
            "gradient_accumulation_steps": 8,
            "lr_scheduler_type": "cosine",
            "logging_steps": 10,
            "save_steps": 100,
            "learning_rate": 1e-4,
            "num_train_epochs": 6.0,
            "max_samples": 2000,
            "max_grad_norm": 1.0,
            "val_size": 0.2,
            "cutoff_len": 2048,
            "hf_hub_token": "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",
            "fp16": True,
            "plot_loss": True,
            "evaluation_strategy": "steps",
        },
        "export_model_config": {
            "model_name_or_path": "meta-llama/Llama-2-7b-chat-hf",
            "adapter_name_or_path": "/content/drive/MyDrive/models/llama2_7b_8batch",
            "finetuning_type": "lora",
            "template": "llama2",
            "hf_hub_token": "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",
            "export_dir": "/content/drive/MyDrive/models/ft_gemma7b_lora8batch",
        },
        "chat_model_config": {
            "model_name_or_path": "/content/drive/MyDrive/models/ft_gemma7b_lora8batch",
            "template": "llama2",
        },
        "input_file": "nex_dataset/test/category_test_en.json",
        "output_file": "/content/drive/MyDrive/models/llama2_7b_lora8batch.json",
        "result_key": "llama7b_lora8batch",
    },
    "bloom-560m": {
        "run_exp_config": {
            "stage": "sft",
            "do_train": True,
            "do_eval": True,
            "model_name_or_path": "bigscience/bloom-560m",
            "dataset": "medical_report_category",
            "finetuning_type": "lora",
            "lora_rank": 8,
            "lora_alpha": 16,
            "lora_dropout": 0.1,
            "lora_target": "all",
            "output_dir": "/content/drive/MyDrive/models/ft_bloom_test",
            "per_device_train_batch_size": 2,
            "per_device_eval_batch_size": 1,
            "gradient_accumulation_steps": 8,
            "lr_scheduler_type": "cosine",
            "logging_steps": 10,
            "save_steps": 100,
            "learning_rate": 1e-4,
            "num_train_epochs": 2.0,
            "max_samples": 200,
            "max_grad_norm": 1.0,
            "val_size": 0.2,
            "cutoff_len": 1024,
            "hf_hub_token": "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",
            "fp16": True,
            "plot_loss": True,
            "evaluation_strategy": "steps",
        },
        "export_model_config": {
            "model_name_or_path": "bigscience/bloom-560m",
            "adapter_name_or_path": "/content/drive/MyDrive/models/ft_bloom_test",
            "finetuning_type": "lora",
            "hf_hub_token": "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",
            "export_dir": "/content/drive/MyDrive/models/ft_bloom",
        },
        "chat_model_config": {
            "model_name_or_path": "/content/drive/MyDrive/models/ft_bloom",
        },
        "input_file": "nex_dataset/test/category_test_en.json",
        "output_file": "/content/drive/MyDrive/models/bloom560m.json",
        "result_key": "bloom560m",
    },
}

prompt_instruct = "Your task is to determine the type of medical report entered. The report type options are: ['Other', 'Examination Record', 'Doctor's Order', 'Prescription', 'Injection', 'Expense', 'Physical Examination Report' ', 'Gene testing', 'Surgery record', 'Examination record', 'Treatment record', 'Pathology report', 'Disease course record', 'Outpatient medical record', 'Discharge and admission record', 'Informed consent', ' Other consultation records', 'Pathological consultation records', 'Other disease diagnosis certificates', 'Outpatient disease diagnosis certificates', 'Inpatient and admission disease diagnosis certificates']\nMedical report:|||Content|||\nOutput format: directly select the most appropriate item from the options and output it, without explaining or outputting redundant content"
