### model
model_name_or_path: /mnt/windows/Users/Admin/LLM/models/shenzhi-wang/Gemma-2-9B-Chinese-Chat
### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
# datasets = """pathology_sft,basic_information_sft,cancer_treatment_sft,comorbid_disease_sft,
# date_unit_sft,diagnosis_sft,disease_sft,genetic_testing_sft,imaging_sft,immunization_sft,symptom_sft,treatment_drug_plan_sft"""

dataset: pathology_sft,basic_information_sft,cancer_treatment_sft,comorbid_disease_sft,date_unit_sft,diagnosis_sft,disease_sft,genetic_testing_sft,imaging_sft,immunization_sft,symptom_sft,treatment_drug_plan_sft
template: gemma
cutoff_len: 1024
max_samples: 512
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/windows/Users/Admin/LLM/models/shenzhi-wang/nexusera_lora_extract_gemma
# resume_from_checkpoint: /mnt/windows/Users/Admin/LLM/models/qwen/nexusera_lora_extract
logging_steps: 512
save_steps: 1024
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
weight_decay: 0.01

### eval
do_eval: True
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 512

### lora
lora_dropout: 0.05
lora_rank: 8
lora_target: all

use_unsloth: True
