### model
model_name_or_path: /mnt/windows/Users/Admin/LLM/models/shenzhi-wang/Llama3-8B-Chinese-Chat

### method
stage: sft
do_train: true
finetuning_type: lora
# loraplus_lr_ratio: 2.0 #
mixture_of_depths: convert # load, convert F1:0.959

# pissa 
pissa_init: true
pissa_iter: 4
pissa_convert: true

### dataset
# datasets = """pathology_sft,basic_information_sft,cancer_treatment_sft,comorbid_disease_sft,
# date_unit_sft,diagnosis_sft,disease_sft,genetic_testing_sft,imaging_sft,immunization_sft,symptom_sft,treatment_drug_plan_sft"""

dataset: treatment_drug_plan_sft
template: llama3
cutoff_len: 1024
max_samples: 100
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/windows/Users/Admin/LLM/models/shenzhi-wang/lora_Llama3-8B
# resume_from_checkpoint: /mnt/windows/Users/Admin/LLM/models/shenzhi-wang/lora_Llama3-8B
logging_steps: 64
save_steps: 128
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine_with_restarts
# lr_scheduler_kwargs: cosine_with_min_lr
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
weight_decay: 0.01

### eval
do_eval: True
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 64

### lora
lora_dropout: 0.05
lora_rank: 64
lora_alpha: 128 #64
lora_target: q_proj,v_proj,o_proj,k_proj,up_proj

use_unsloth: True
