### model
model_name_or_path: /mnt/windows/Users/Admin/LLM/models/shenzhi-wang/Mistral-7B-v0.3-Chinese-Chat/

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
# datasets = """pathology_sft,basic_information_sft,cancer_treatment_sft,comorbid_disease_sft,
# date_unit_sft,diagnosis_sft,disease_sft,genetic_testing_sft,imaging_sft,immunization_sft,symptom_sft,treatment_drug_plan_sft"""

dataset: cancer_treatment_sft,treatment_drug_plan_sft
template: mistral
cutoff_len: 1400
max_samples: 100
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/windows/Users/Admin/LLM/models/shenzhi-wang/test_mistral
logging_steps: 50
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
weight_decay: 0.01

### eval
do_eval: True
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 50

### lora
lora_dropout: 0.05
lora_rank: 64
lora_target: all

use_unsloth: True
