# 问答模型
model_name_or_path: /mnt/windows/Users/Admin/LLM/models/qwen/Qwen2-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora

dataset: 肿瘤科所有数据
template: qwen
cutoff_len: 1024
max_samples: 500
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/windows/Users/Admin/LLM/models/qwen/test_7B/Qwen2-7B-Instruct-turmo
# resume_from_checkpoint: /mnt/windows/Users/Admin/LLM/models/qwen/test_7B/Qwen2-7B-Instruct-turmo
logging_steps: 200
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 2.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine_with_restarts
# lr_scheduler_kwargs: cosine_with_min_lr
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
weight_decay: 0.05

### eval
do_eval: True
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 200

### lora
lora_dropout: 0.05
lora_rank: 16
lora_alpha: 32
lora_target: all

# use_unsloth: True
