# 问答模型
model_name_or_path: /mnt/windows/Users/Admin/LLM/models/qwen/Qwen2-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora

dataset: gene_fullDose
template: qwen
cutoff_len: 1200
max_samples: 500
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/windows/Users/Admin/LLM/models/qwen/test_7B/Qwen2-7B-Instruct-full_dose
### output
# resume_from_checkpoint: /mnt/windows/Users/Admin/LLM/models/qwen/nexusera_lora_extract
logging_steps: 64
save_steps: 128
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine_with_restarts
# lr_scheduler_kwargs: cosine_with_min_lr
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
weight_decay: 0.01

### eval
do_eval: True
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 64

### lora
lora_dropout: 0.1
lora_rank: 64
lora_alpha: 128
lora_target: q_proj,v_proj,o_proj,k_proj,up_proj
