### model
model_name_or_path: /mnt/windows/Users/Admin/LLM/models/qwen/Qwen2-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
### dataset
# datasets = """TCM"""

dataset: TCM
template: qwen
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/windows/Users/Admin/LLM/models/qwen/TCM/tcm_qwen2_800
# resume_from_checkpoint: /mnt/windows/Users/Admin/LLM/models/qwen/nexusera_lora_extract
logging_steps: 100
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
num_train_epochs: 5.0
lr_scheduler_type: cosine
# lr_scheduler_kwargs: cosine_with_min_lr
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
weight_decay: 0.01

### eval
do_eval: True
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 100

### lora
lora_dropout: 0.01
lora_rank: 32
lora_alpha: 64
lora_target: all

# use_unsloth: True
