### model
model_name_or_path: ../wwyuuuu/Qwen2___5-SFT

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj
pref_beta: 0.1
pref_loss: sigmoid  # [sigmoid (dpo), orpo, simpo]

### dataset
dataset: reward
template: qwen
cutoff_len: 1024
max_samples: 5000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../wwyuuuu/dpo
logging_steps: 100
save_steps: 400
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
# use_unsloth: True

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
lora_rank: 32
lora_dropout: 0.05